import * as fs from 'fs/promises';
import * as os from 'os';
import * as path from 'path';
import { execFile } from 'child_process';
import { promisify } from 'util';
import createIgnore from 'ignore';
import { buildProjectTreeIndex } from './tree';
import {
  DEFAULT_IGNORE_PATTERNS,
  DEFAULT_LOCAL_IGNORE_CONTENT,
  ensureLocalIgnoreFile,
  isAlwaysLocal,
  LOCAL_IGNORE_NAME,
  manifestPath,
  MAX_METADATA_JSON_BYTES,
  metadataPath,
  readTextFileBounded,
  setLocalIgnoreRules,
  writeBaseDoc,
  writeManifest
} from './manifest';
import type { ManifestFile, OverleafCodexManifest, ProjectSummary } from './types';
import { OverleafClient } from './overleafClient';
import { expandHome, isTextLike, sanitizeProjectFolderName, sha1 } from './util';
import { registerSharedMirror } from './sharedState';
import { scanLocalProject } from './syncStatus';
import { extractDocumentclassDeclaration, stripTexComments } from '../utils';
import { mapWithConcurrency, mapWithDynamicByteConcurrency, type DynamicByteReservation } from './syncHealthService';

const execFileAsync = promisify(execFile);

const AGENTS_CONTENT = `# AGENTS.md

This folder is a real local mirror of an Overleaf project.

- Edit LaTeX source files such as .tex, .bib, .sty and .cls normally.
- Do not edit .overleaf-codex/**; it contains sync metadata, build output and conflict copies.
- Edit .overleaf-codexignore to keep project-specific local or generated paths out of Overleaf sync.
- Do not upload or sync .vscode/**; it is local VS Code/LaTeX Workshop configuration only.
- Do not edit generated LaTeX outputs such as .aux, .log, .toc, .synctex.gz or PDFs unless explicitly asked.
- Prefer small, reviewable edits and keep paths stable when collaborators may also be editing in Overleaf.
`;

export const MIRROR_GITIGNORE_CONTENT = `# Generated by Overleaf Codex.
# Keep local sync/build metadata out of Git. Overleaf source files remain tracked.

.overleaf-codex/

# Local build outputs
*.aux
*.bbl
*.bcf
*.bcf-*
*.blg
*.fdb_latexmk
*.fls
*.lof
*.log
*.lot
*.out
*.run.xml
*.synctex
*.synctex.gz
*.synctex(busy)
*.toc
*.xdv
*-SAVE-ERROR
main.pdf
output.pdf

# Local credentials / OS noise
cookie*
.DS_Store
`;

export interface CreateProjectMirrorOptions {
  register?: (root: string) => Promise<unknown>;
  taskConcurrency?: number;
  maxInFlightBytes?: number;
}

export function projectMirrorRoot(parentRoot: string, project: ProjectSummary): string {
  return path.join(expandHome(parentRoot), sanitizeProjectFolderName(project.name, project.id));
}

export async function createProjectMirror(
  client: OverleafClient,
  project: ProjectSummary,
  parentRoot: string,
  options: CreateProjectMirrorOptions = {}
): Promise<string> {
  const targetRoot = projectMirrorRoot(parentRoot, project);
  await fs.mkdir(path.dirname(targetRoot), { recursive: true });
  try {
    await fs.mkdir(targetRoot);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new Error(`Mirror target already exists: ${targetRoot}`);
    }
    throw error;
  }

  let session: Awaited<ReturnType<OverleafClient['connectSocket']>> | undefined;
  try {
    session = await client.connectSocket(project.id);
    const joined = session.getProject();
    if (!joined) throw new Error('Realtime connection did not provide a project tree.');
    const index = buildProjectTreeIndex(client.getServerUrl(), project.id, project.name, joined);
    await mapWithConcurrency(
      index.folders.filter(folder => Boolean(folder.path)),
      options.taskConcurrency ?? 4,
      async folder => { await fs.mkdir(path.join(targetRoot, folder.path), { recursive: true }); }
    );
    await mapWithDynamicByteConcurrency(
      index.files,
      options.taskConcurrency ?? 4,
      options.maxInFlightBytes ?? 32 * 1024 * 1024,
      async (file, reservation) => writeInitialFile(client, session!, project.id, targetRoot, file, reservation)
    );
    for (const name of ['output', 'conflicts', path.join('base', 'docs'), 'trash']) {
      await fs.mkdir(metadataPath(targetRoot, name), { recursive: true });
    }
    await ensureLocalIgnoreFile(targetRoot);
    await writeManifest(targetRoot, index.manifest);
    await writeMirrorSupportFiles(targetRoot, index.manifest.rootDocPath, index.manifest.compiler);
    await initializeMirrorGitRepository(targetRoot, `Initial Overleaf mirror: ${project.name}`);
  } catch (error) {
    await fs.rm(targetRoot, { recursive: true, force: true });
    throw error;
  } finally {
    session?.disconnect();
  }
  await (options.register ?? registerSharedMirror)(targetRoot);
  return targetRoot;
}

async function writeInitialFile(
  client: OverleafClient,
  session: Awaited<ReturnType<OverleafClient['connectSocket']>>,
  projectId: string,
  root: string,
  file: ManifestFile,
  reservation?: DynamicByteReservation
): Promise<void> {
  const target = path.join(root, file.path);
  await fs.mkdir(path.dirname(target), { recursive: true });
  if (file.entityType === 'doc') {
    const joined = await session.joinDoc(file.entityId);
    try {
      await reservation?.reserve(Buffer.byteLength(joined.content, 'utf8'));
      await fs.writeFile(target, joined.content, 'utf8');
      file.version = joined.version;
      file.binary = !isTextLike(file.path);
      file.sha1 = sha1(joined.content);
      file.baseHash = await writeBaseDoc(root, file.entityId, joined.content);
    } finally {
      await session.leaveDoc(file.entityId).catch(() => undefined);
    }
  } else {
    const result = await client.downloadProjectFileToPath(projectId, file.entityId, target, {
      onSize: async size => { await reservation?.reserve(size); }
    });
    file.binary = true;
    file.sha1 = result.sha1;
    file.remoteSize = result.size;
    file.remoteBlobHash ??= result.gitBlobHash;
  }
}

/** A brand-new Overleaf project holds only its default main.tex; more than this is unexpected. */
const MAX_ENTITIES_IN_FRESH_PROJECT = 2;

/**
 * Joins a project created moments ago and removes the default content Overleaf seeds it with,
 * returning a manifest that describes the now-empty project.
 *
 * Overleaf hands back a `template: 'none'` project already holding a main.tex. The size guard
 * refuses to clear anything larger than that: it should never trigger, but being wrong here would
 * mean deleting someone's work, so it fails closed.
 */
async function emptyFreshProject(
  client: OverleafClient,
  projectId: string,
  projectName: string
): Promise<OverleafCodexManifest> {
  const session = await client.connectSocket(projectId);
  try {
    const joined = session.getProject();
    if (!joined) throw new Error('Realtime connection did not provide a project tree.');
    const index = buildProjectTreeIndex(client.getServerUrl(), projectId, projectName, joined);
    const existing = Object.values(index.manifest.files);
    if (existing.length > MAX_ENTITIES_IN_FRESH_PROJECT) {
      throw new Error(
        `New Overleaf project unexpectedly contains ${existing.length} files; refusing to clear it.`
      );
    }
    for (const file of existing) {
      await client.deleteEntity(projectId, file.entityType, file.entityId);
      delete index.manifest.files[file.path];
    }
    index.manifest.rootDocId = undefined;
    index.manifest.rootDocPath = undefined;
    return index.manifest;
  } finally {
    session.disconnect();
  }
}

async function createMetadataDirectories(root: string): Promise<void> {
  for (const name of ['output', 'conflicts', path.join('base', 'docs'), 'trash']) {
    await fs.mkdir(metadataPath(root, name), { recursive: true });
  }
}

export interface CreateRemoteProjectOptions {
  /** Populates the freshly prepared, still-empty mirror. Throwing here rolls the project back. */
  scaffold(root: string): Promise<void>;
  /** Uploads the scaffolded files. Runs after the manifest exists, so failures do not roll back. */
  publish(root: string, client: OverleafClient, projectId: string): Promise<void>;
  register?(root: string): Promise<unknown>;
}

export interface CreateRemoteProjectResult {
  root: string;
  projectId: string;
  /** False when the project exists and is tracked but publishing its contents did not finish. */
  published: boolean;
  publishError?: Error;
}

/**
 * Creates an Overleaf project and turns it into a local mirror holding `scaffold`'s output.
 *
 * This is createProjectMirror run backwards: instead of materialising an existing project locally,
 * it makes an empty one remote-side and pushes local content into it. Overleaf hands back a
 * project containing a default main.tex, which is removed so the scaffolded files are the only
 * thing the project has ever had.
 *
 * Rollback is deliberately asymmetric. Up to the point the manifest lands, a failure deletes both
 * the remote project and the local folder, because a half-made mirror is worse than none. After
 * the manifest exists the folder is a legitimate mirror whose upload can simply be retried, so a
 * publish failure is reported rather than thrown and nothing is destroyed.
 */
export async function createRemoteProjectMirror(
  client: OverleafClient,
  projectName: string,
  parentRoot: string,
  options: CreateRemoteProjectOptions
): Promise<CreateRemoteProjectResult> {
  const projectId = await client.createProject(projectName);
  const summary: ProjectSummary = { id: projectId, name: projectName };
  const targetRoot = projectMirrorRoot(parentRoot, summary);

  let manifestWritten = false;
  try {
    await fs.mkdir(path.dirname(targetRoot), { recursive: true });
    await fs.mkdir(targetRoot);

    const manifest = await emptyFreshProject(client, projectId, projectName);
    await options.scaffold(targetRoot);

    await createMetadataDirectories(targetRoot);
    await ensureLocalIgnoreFile(targetRoot);
    await writeManifest(targetRoot, manifest);
    manifestWritten = true;
    await writeMirrorSupportFiles(targetRoot, manifest.rootDocPath, manifest.compiler);
    await initializeMirrorGitRepository(targetRoot, `Initial Overleaf project: ${projectName}`);
  } catch (error) {
    if (!manifestWritten) {
      // This function created targetRoot moments ago, so removing it whole is safe here - unlike
      // publishLocalFolder, where the directory belongs to the user.
      await fs.rm(targetRoot, { recursive: true, force: true }).catch(() => undefined);
      await client.deleteProject(projectId).catch(() => undefined);
    }
    throw error;
  }

  await (options.register ?? registerSharedMirror)(targetRoot);

  try {
    await options.publish(targetRoot, client, projectId);
  } catch (error) {
    // The mirror is real and tracked; retrying the sync is a better answer than deleting it.
    return { root: targetRoot, projectId, published: false, publishError: error as Error };
  }
  return { root: targetRoot, projectId, published: true };
}

/** A manifest with nothing tracked, used to ask scanLocalProject what a folder would sync. */
function untrackedManifest(): OverleafCodexManifest {
  return {
    schemaVersion: 3,
    serverUrl: '',
    projectId: '',
    projectName: '',
    files: {},
    folders: { '': { path: '', entityId: '' } },
    ignore: [...DEFAULT_IGNORE_PATTERNS],
    lastSyncAt: new Date(0).toISOString()
  };
}

export interface LocalPublishPreview {
  files: Array<{ path: string; size: number }>;
  totalBytes: number;
  /** Folders below root that are already mirrors. Publishing would upload their files a second time. */
  nestedMirrors: string[];
}

/**
 * Lists what publishing `root` would upload, applying the same rules a sync would: the manifest
 * ignore patterns, the toolkit exclusions, the folder's .overleaf-codexignore (or the default list
 * when it has none) for untracked paths, and isAlwaysLocal. Build output, PDFs, `.git` and editor
 * state therefore never appear here.
 */
export async function previewLocalPublish(
  root: string,
  isExcluded: (relPath: string) => boolean = () => false
): Promise<LocalPublishPreview> {
  const manifest = untrackedManifest();
  // Publishing keeps an existing ignore file, so the sync will apply it; the preview must too.
  setLocalIgnoreRules(manifest, await readTextFileBounded(path.join(root, LOCAL_IGNORE_NAME), MAX_METADATA_JSON_BYTES)
    .catch(() => DEFAULT_LOCAL_IGNORE_CONTENT));
  const scan = await scanLocalProject(root, manifest);
  const files = scan.files
    .filter(relPath => !isAlwaysLocal(relPath) && !isExcluded(relPath))
    .map(relPath => ({ path: relPath, size: scan.fileMetadata.get(relPath)?.size ?? 0 }))
    .sort((a, b) => a.path.localeCompare(b.path));
  const nestedMirrors = (await Promise.all(scan.folders.map(async folder =>
    await exists(manifestPath(path.join(root, folder))) ? folder : undefined
  ))).filter((folder): folder is string => folder !== undefined);
  return { files, totalBytes: files.reduce((sum, file) => sum + file.size, 0), nestedMirrors };
}

/** The nearest folder above `root` that is a mirror, if any. */
export async function findEnclosingMirror(root: string): Promise<string | undefined> {
  let current = path.resolve(root);
  while (path.dirname(current) !== current) {
    current = path.dirname(current);
    if (await exists(manifestPath(current))) return current;
  }
  return undefined;
}

/**
 * Renders paths as anchored .overleaf-codexignore entries that leave exactly those files out.
 *
 * The ignore library has no escape for `?`, which stays a one-character wildcard, so the entries
 * are checked against every candidate and rejected if they would also catch a file nobody asked
 * to leave out.
 */
export function localIgnoreEntries(excluded: string[], candidates: string[]): string[] {
  const entries = excluded.map(relPath => {
    if (/[\r\n]/.test(relPath)) throw new Error(`Cannot leave out ${JSON.stringify(relPath)}: its name contains a line break.`);
    return `/${relPath.replace(/[\\*[]/g, match => `\\${match}`).replace(/ +$/, spaces => spaces.replace(/ /g, '\\ '))}`;
  });
  const matcher = createIgnore().add(entries);
  const wanted = new Set(excluded);
  const collateral = candidates.filter(relPath => !wanted.has(relPath) && matcher.ignores(relPath));
  const missed = excluded.filter(relPath => !matcher.ignores(relPath));
  if (collateral.length || missed.length) {
    throw new Error(
      `The selected files cannot be left out exactly (${[...missed, ...collateral].join(', ')}). `
        + `Add them to ${LOCAL_IGNORE_NAME} by hand instead.`
    );
  }
  return entries;
}

/**
 * Returns the .tex files that declare a \documentclass, i.e. the ones that could be a root
 * document. main.tex sorts first, then shallower paths, so a caller offering a choice leads with
 * the conventional answer. Comments are stripped first so a commented-out declaration is ignored.
 */
export async function detectRootDocuments(root: string, candidatePaths: string[]): Promise<string[]> {
  const found: string[] = [];
  for (const relPath of candidatePaths) {
    if (!/\.tex$/i.test(relPath)) continue;
    const text = await readTextFileBounded(path.join(root, relPath), MAX_METADATA_JSON_BYTES).catch(() => '');
    if (extractDocumentclassDeclaration(stripTexComments(text))) found.push(relPath);
  }
  const depth = (relPath: string) => relPath.split('/').length;
  return found.sort((a, b) => {
    const aMain = path.posix.basename(a) === 'main.tex' ? 0 : 1;
    const bMain = path.posix.basename(b) === 'main.tex' ? 0 : 1;
    return aMain - bMain || depth(a) - depth(b) || a.localeCompare(b);
  });
}

const PUBLISHED_IN_PLACE_MARKER = 'origin.json';

/**
 * True when `root` became a mirror by being published in place, i.e. the folder was the user's
 * before it was ever a mirror. Deleting such a mirror must never delete the folder.
 */
export async function isPublishedInPlace(root: string): Promise<boolean> {
  const raw = await readTextFileBounded(metadataPath(root, PUBLISHED_IN_PLACE_MARKER), MAX_METADATA_JSON_BYTES).catch(() => undefined);
  if (raw === undefined) return false;
  try {
    return (JSON.parse(raw) as { kind?: unknown }).kind === 'published-in-place';
  } catch {
    // Unreadable but present: err on the side of keeping the user's folder.
    return true;
  }
}

export interface PublishLocalFolderOptions {
  /** Uploads the folder's content. Runs after the manifest exists, so failures do not roll back. */
  publish(root: string, client: OverleafClient, projectId: string): Promise<void>;
  register?(root: string): Promise<unknown>;
  /** Files to keep out of the project. They go into .overleaf-codexignore, so later syncs skip them too. */
  excludedPaths?: string[];
}

export interface PublishLocalFolderResult {
  root: string;
  projectId: string;
  published: boolean;
  publishError?: Error;
  /** Support files that already existed and were left as the user had them. */
  keptFiles: string[];
}

/**
 * Publishes an existing local folder to a new Overleaf project, turning the folder itself into
 * the mirror.
 *
 * Unlike createRemoteProjectMirror, this function does not own `root`: it belongs to the user and
 * may hold years of work. So rollback removes only what this call created - the metadata folder,
 * the ignore file or the lines appended to it, and the remote project - and never the folder
 * itself. Support files the user already has are kept rather than overwritten. Everything that
 * can be checked locally is checked before the remote project exists.
 */
export async function publishLocalFolder(
  client: OverleafClient,
  root: string,
  projectName: string,
  rootDocPath: string,
  options: PublishLocalFolderOptions
): Promise<PublishLocalFolderResult> {
  if (await exists(manifestPath(root))) {
    throw new Error('This folder is already an Overleaf mirror.');
  }
  const enclosing = await findEnclosingMirror(root);
  if (enclosing) {
    throw new Error(`This folder is inside the Overleaf mirror at ${enclosing}; its files already sync with that project.`);
  }
  const preview = await previewLocalPublish(root);
  if (preview.nestedMirrors.length) {
    throw new Error(`This folder contains another Overleaf mirror (${preview.nestedMirrors.join(', ')}); publish a folder that does not.`);
  }
  const candidates = preview.files.map(file => file.path);
  if (!candidates.includes(rootDocPath)) {
    throw new Error(`The main document ${rootDocPath} is not among the files that would be uploaded.`);
  }
  // Paths the folder no longer has would not be uploaded anyway, so they need no entry.
  const excluded = [...new Set(options.excludedPaths ?? [])].filter(relPath => candidates.includes(relPath));
  if (excluded.includes(rootDocPath)) throw new Error('The main document cannot be left out of the project.');
  const ignoreEntries = excluded.length ? localIgnoreEntries(excluded, candidates) : [];

  // Record what exists before touching anything, so rollback can tell ours from theirs.
  const metadataRoot = metadataPath(root);
  const ignoreFile = path.join(root, LOCAL_IGNORE_NAME);
  const metadataExisted = await exists(metadataRoot);
  // Only ever appended to, so truncating back to this size undoes exactly what was added.
  const ignoreSizeBefore = await fs.stat(ignoreFile).then(stat => stat.size, () => undefined);

  const projectId = await client.createProject(projectName);
  let manifestWritten = false;
  let keptFiles: string[] = [];
  try {
    const manifest = await emptyFreshProject(client, projectId, projectName);
    // The root doc has no remote entity yet, so only the path is known; the id arrives with it.
    manifest.rootDocPath = rootDocPath;
    await createMetadataDirectories(root);
    // Written before the manifest so no moment exists where this is a mirror that looks disposable.
    await fs.writeFile(
      metadataPath(root, PUBLISHED_IN_PLACE_MARKER),
      `${JSON.stringify({ kind: 'published-in-place', at: new Date().toISOString() }, null, 2)}\n`,
      'utf8'
    );
    await ensureLocalIgnoreFile(root);
    // Before the manifest: once it exists a sync may run, and it must already skip these.
    if (ignoreEntries.length) {
      await fs.appendFile(ignoreFile, `\n# Left out when this folder was published to Overleaf.\n${ignoreEntries.join('\n')}\n`, 'utf8');
    }
    await writeManifest(root, manifest);
    manifestWritten = true;
    keptFiles = await writeMirrorSupportFiles(root, rootDocPath, manifest.compiler, { overwriteExisting: false });
  } catch (error) {
    if (!manifestWritten) {
      if (!metadataExisted) await fs.rm(metadataRoot, { recursive: true, force: true }).catch(() => undefined);
      else await fs.rm(metadataPath(root, PUBLISHED_IN_PLACE_MARKER), { force: true }).catch(() => undefined);
      if (ignoreSizeBefore === undefined) await fs.rm(ignoreFile, { force: true }).catch(() => undefined);
      else await fs.truncate(ignoreFile, ignoreSizeBefore).catch(() => undefined);
      await client.deleteProject(projectId).catch(() => undefined);
    }
    throw error;
  }

  await (options.register ?? registerSharedMirror)(root);

  try {
    await options.publish(root, client, projectId);
  } catch (error) {
    return { root, projectId, published: false, publishError: error as Error, keptFiles };
  }
  return { root, projectId, published: true, keptFiles };
}

/**
 * Writes the editor, latexmk and agent files a mirror relies on. Returns the paths it left alone.
 *
 * A mirror created from scratch owns its folder, so overwriting is right there. A folder published
 * in place already belongs to the user and may carry its own versions of every one of these files;
 * `overwriteExisting: false` keeps theirs and reports what was kept, so they can merge by hand.
 */
export async function writeMirrorSupportFiles(
  root: string,
  rootDocPath?: string,
  compiler?: string,
  options: { overwriteExisting?: boolean } = {}
): Promise<string[]> {
  const overwrite = options.overwriteExisting ?? true;
  const rootDir = rootDocPath ? path.posix.dirname(rootDocPath) : '.';
  const writers: Array<[string, () => Promise<void>]> = [
    ['.vscode/settings.json', () => writeLocalVsCodeSettings(root, rootDocPath, compiler)],
    [path.posix.join(rootDir, '.latexmkrc'), () => writeLocalLatexmkRc(root, rootDocPath)],
    ['AGENTS.md', () => fs.writeFile(path.join(root, 'AGENTS.md'), AGENTS_CONTENT, 'utf8')]
  ];
  const kept: string[] = [];
  await Promise.all(writers.map(async ([relative, write]) => {
    if (!overwrite && await exists(path.join(root, relative))) {
      kept.push(relative);
      return;
    }
    await write();
  }));
  return kept.sort();
}

export async function initializeMirrorGitRepository(
  root: string,
  commitMessage = 'Initial Overleaf mirror'
): Promise<void> {
  await fs.mkdir(root, { recursive: true });
  await fs.writeFile(path.join(root, '.gitignore'), MIRROR_GITIGNORE_CONTENT, 'utf8');
  if (!await exists(path.join(root, '.git'))) {
    await runGit(root, ['init']);
    await runGit(root, ['add', '-A']);
    const staged = await runGit(root, ['diff', '--cached', '--quiet']).then(
      () => false,
      error => isGitDiffExitCode(error) ? true : Promise.reject(error)
    );
    if (staged) {
      await runGit(root, [
        '-c', 'user.name=Overleaf Codex',
        '-c', 'user.email=overleaf-codex@local',
        'commit',
        '-m', commitMessage
      ]);
    }
    return;
  }
  await runGit(root, ['add', '.gitignore']);
}

async function writeLocalVsCodeSettings(root: string, rootDocPath?: string, compiler?: string): Promise<void> {
  const settingsPath = path.join(root, '.vscode', 'settings.json');
  await fs.mkdir(path.dirname(settingsPath), { recursive: true });
  const rootFile = rootDocPath ? `./${rootDocPath}` : undefined;
  const rootDir = rootDocPath ? path.posix.dirname(rootDocPath) : '.';
  const texFile = rootDocPath ? path.posix.basename(rootDocPath) : '%DOC%';
  const engine = compiler === 'pdflatex' ? '-pdf' : compiler === 'lualatex' ? '-lualatex' : '-xelatex';
  const outputDir = '.overleaf-codex/local-build';
  const outputDirFromRootDoc = path.posix.relative(rootDir, outputDir) || '.';
  const workspaceFromRootDoc = path.posix.relative(rootDir, '.') || '.';
  const biberCacheDir = path.join(os.tmpdir(), 'overleaf-codex-biber', sha1(root).slice(0, 12));
  const searchPrefix = rootDir === '.' ? '.:src/source//:' : `.:${workspaceFromRootDoc}//:src/source//:`;
  const compileCommand = [
    `mkdir -p ${shellQuote(outputDir)}`,
    `mkdir -p ${shellQuote(biberCacheDir)}`,
    `cd ${shellQuote(rootDir)}`,
    [
      'find . -type d',
      "-not -path './.git*'",
      "-not -path './.overleaf-codex*'",
      "-not -path './.vscode*'",
      `-exec mkdir -p ${shellQuote(`${outputDirFromRootDoc}/{}`)} \\;`
    ].join(' '),
    [
      'latexmk', '-synctex=1', '-interaction=nonstopmode', '-file-line-error', engine,
      `-outdir=${shellQuote(outputDirFromRootDoc)}`,
      `-auxdir=${shellQuote(outputDirFromRootDoc)}`,
      shellQuote(texFile)
    ].join(' ')
  ].join(' && ');
  const settings = {
    'latex-workshop.latex.rootFile.doNotPrompt': true,
    'latex-workshop.latex.rootFile.useSubFile': false,
    ...(rootFile ? {
      'latex-workshop.latex.search.rootFiles.include': [rootFile.replace(/^\.\//, '')],
      'latex-workshop.latex.search.rootFiles.exclude': ['**/*.sty', '**/*.cls']
    } : {}),
    'latex-workshop.latex.recipe.default': 'latexmk (local mirror)',
    'latex-workshop.latex.autoBuild.run': 'onSave',
    'latex-workshop.latex.outDir': '%WORKSPACE_FOLDER%/.overleaf-codex/local-build',
    'latex-workshop.latex.tools': [{
      name: 'latexmk-local-mirror', command: 'bash', args: ['-lc', compileCommand],
      env: {
        TEXINPUTS: searchPrefix,
        GINPUTS: searchPrefix,
        BIBINPUTS: searchPrefix,
        PAR_GLOBAL_TEMP: biberCacheDir,
        PAR_TEMP: biberCacheDir
      }
    }],
    'latex-workshop.latex.recipes': [{ name: 'latexmk (local mirror)', tools: ['latexmk-local-mirror'] }]
  };
  await fs.writeFile(settingsPath, `${JSON.stringify(settings, null, 2)}\n`, 'utf8');
}

async function writeLocalLatexmkRc(root: string, rootDocPath?: string): Promise<void> {
  const rootDir = rootDocPath ? path.posix.dirname(rootDocPath) : '.';
  const rcPath = path.join(root, rootDir, '.latexmkrc');
  const outputDir = '.overleaf-codex/local-build';
  const outputDirFromRootDoc = path.posix.relative(rootDir, outputDir) || '.';
  const workspaceFromRootDoc = path.posix.relative(rootDir, '.') || '.';
  const searchPrefix = rootDir === '.' ? '.:src/source//:' : `.:${workspaceFromRootDoc}//:src/source//:`;
  const biberCacheDir = path.join(os.tmpdir(), 'overleaf-codex-biber', sha1(root).slice(0, 12));
  const content = [
    '# Generated by Overleaf Codex for local VS Code/LaTeX Workshop builds.',
    '# This file is local-only and should not be synced back to Overleaf.',
    "if (-f 'latexmkrc') {", "  do './latexmkrc';", '}',
    'use File::Find;', 'use File::Path qw(make_path);',
    `my $overleaf_codex_build_dir = ${perlSingleQuote(outputDirFromRootDoc)};`,
    `my $overleaf_codex_biber_cache = ${perlSingleQuote(biberCacheDir)};`,
    'make_path($overleaf_codex_build_dir);', 'make_path($overleaf_codex_biber_cache);',
    'find({', '  wanted => sub {', '    return unless -d $_;',
    '    my $rel = $File::Find::name;', "    return if $rel eq '.';", "    $rel =~ s#^\\./##;",
    "    return if $rel =~ m#^\\.git(/|$)#;", "    return if $rel =~ m#^\\.overleaf-codex(/|$)#;",
    "    return if $rel =~ m#^\\.vscode(/|$)#;", '    make_path("$overleaf_codex_build_dir/$rel");',
    '  },', '  no_chdir => 1', "}, '.');",
    '$out_dir = $overleaf_codex_build_dir;', '$aux_dir = $overleaf_codex_build_dir;',
    `$ENV{'TEXINPUTS'} = ${perlSingleQuote(searchPrefix)} . ($ENV{'TEXINPUTS'} // '');`,
    `$ENV{'GINPUTS'} = ${perlSingleQuote(searchPrefix)} . ($ENV{'GINPUTS'} // '');`,
    `$ENV{'BIBINPUTS'} = ${perlSingleQuote(searchPrefix)} . ($ENV{'BIBINPUTS'} // '');`,
    "$ENV{'PAR_GLOBAL_TEMP'} = $overleaf_codex_biber_cache;",
    "$ENV{'PAR_TEMP'} = $overleaf_codex_biber_cache;", ''
  ].join('\n');
  await fs.mkdir(path.dirname(rcPath), { recursive: true });
  await fs.writeFile(rcPath, content, 'utf8');
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function perlSingleQuote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

async function runGit(cwd: string, args: string[]): Promise<string> {
  const result = await execFileAsync('git', args, { cwd, encoding: 'utf8', maxBuffer: 1024 * 1024 * 10 });
  return `${result.stdout ?? ''}${result.stderr ?? ''}`;
}

function isGitDiffExitCode(error: unknown): boolean {
  return Boolean(error) && typeof error === 'object' && (error as { code?: number }).code === 1;
}

async function exists(target: string): Promise<boolean> {
  return fs.stat(target).then(() => true, () => false);
}
