import * as fs from 'fs/promises';
import * as os from 'os';
import * as path from 'path';
import { execFile } from 'child_process';
import { promisify } from 'util';
import * as vscode from 'vscode';
import { OverleafClient } from './overleafClient';
import { ensureLocalIgnoreFile, manifestPath, metadataPath, readManifest, writeBaseDoc, writeManifest } from './manifest';
import { buildProjectTreeIndex } from './tree';
import { CompileOutputFile, ManifestFile, ProjectSummary } from './types';
import { expandHome, isTextLike, sanitizeProjectFolderName, sha1 } from './util';
import { registerSharedMirror } from './sharedState';

const execFileAsync = promisify(execFile);
const LOCAL_MIRRORS_KEY = 'overleafCodex.localMirrors.v1';

const AGENTS_CONTENT = `# AGENTS.md

This folder is a real local mirror of an Overleaf project.

- Edit LaTeX source files such as .tex, .bib, .sty and .cls normally.
- Do not edit .overleaf-codex/**; it contains sync metadata, build output and conflict copies.
- Edit .overleaf-codexignore to keep project-specific local or generated paths out of Overleaf sync.
- Do not upload or sync .vscode/**; it is local VS Code/LaTeX Workshop configuration only.
- Do not edit generated LaTeX outputs such as .aux, .log, .toc, .synctex.gz or PDFs unless explicitly asked.
- Prefer small, reviewable edits and keep paths stable when collaborators may also be editing in Overleaf.
`;

export const MIRROR_GITIGNORE_CONTENT = `# Generated by Overleaf Codex.
# Keep local sync/build metadata out of Git. Overleaf source files remain tracked.

.overleaf-codex/

# Local build outputs
*.aux
*.bbl
*.bcf
*.bcf-*
*.blg
*.fdb_latexmk
*.fls
*.lof
*.log
*.lot
*.out
*.run.xml
*.synctex
*.synctex.gz
*.synctex(busy)
*.toc
*.xdv
*-SAVE-ERROR
main.pdf
output.pdf

# Local credentials / OS noise
cookie*
.DS_Store
`;

export interface LocalMirrorRecord {
  root: string;
  name: string;
  projectId: string;
  serverUrl: string;
  lastSyncAt?: string;
}

export class MirrorManager {
  constructor(private readonly context: vscode.ExtensionContext) {}

  getConfiguredProjectsRoot(): string {
    const configured = vscode.workspace
      .getConfiguration('overleafCodex')
      .get<string>('localProjectsRoot', '~/Documents/OverleafCodex/projects');
    return expandHome(configured);
  }

  getProjectMirrorRoot(parentRoot: string, project: ProjectSummary): string {
    return path.join(expandHome(parentRoot), sanitizeProjectFolderName(project.name, project.id));
  }

  async mirrorProject(client: OverleafClient, project: ProjectSummary, parentRoot?: string): Promise<string> {
    const projectsRoot = parentRoot ? expandHome(parentRoot) : this.getConfiguredProjectsRoot();
    const targetRoot = this.getProjectMirrorRoot(projectsRoot, project);
    const session = await client.connectSocket(project.id);

    try {
      const joinedProject = session.getProject();
      if (!joinedProject) {
        throw new Error('Realtime connection did not provide a project tree.');
      }

      const index = buildProjectTreeIndex(
        client.getServerUrl(),
        project.id,
        project.name,
        joinedProject
      );

      await fs.mkdir(targetRoot, { recursive: true });

      for (const folder of index.folders) {
        if (folder.path) {
          await fs.mkdir(path.join(targetRoot, folder.path), { recursive: true });
        }
      }

      for (const file of index.files) {
        await this.writeInitialFile(client, session, project.id, targetRoot, file);
      }

      await fs.mkdir(metadataPath(targetRoot), { recursive: true });
      await fs.mkdir(metadataPath(targetRoot, 'output'), { recursive: true });
      await fs.mkdir(metadataPath(targetRoot, 'conflicts'), { recursive: true });
      await fs.mkdir(metadataPath(targetRoot, 'base', 'docs'), { recursive: true });
      await fs.mkdir(metadataPath(targetRoot, 'trash'), { recursive: true });
      await this.writeLocalVsCodeSettings(targetRoot, index.manifest.rootDocPath, index.manifest.compiler);
      await this.writeLocalLatexmkRc(targetRoot, index.manifest.rootDocPath);
      await fs.writeFile(path.join(targetRoot, 'AGENTS.md'), AGENTS_CONTENT, 'utf8');
      await ensureLocalIgnoreFile(targetRoot);
      await writeManifest(targetRoot, index.manifest);
      await this.initializeGitRepository(targetRoot, `Initial Overleaf mirror: ${project.name}`);
      await this.registerLocalMirror(targetRoot);
      return targetRoot;
    } finally {
      session.disconnect();
    }
  }

  async openFolder(root: string): Promise<void> {
    await vscode.commands.executeCommand('vscode.openFolder', vscode.Uri.file(root), false);
  }

  async listLocalMirrors(): Promise<LocalMirrorRecord[]> {
    const registry = await this.getRegisteredMirrors();
    const scanned = await this.scanConfiguredRootMirrors();
    const byRoot = new Map<string, LocalMirrorRecord>();

    for (const mirror of [...registry, ...scanned]) {
      const key = normalizeRoot(mirror.root);
      const existing = byRoot.get(key);
      if (!existing || (mirror.lastSyncAt ?? '').localeCompare(existing.lastSyncAt ?? '') > 0) {
        byRoot.set(key, mirror);
      }
    }

    const mirrors = [...byRoot.values()].sort((a, b) => (b.lastSyncAt ?? '').localeCompare(a.lastSyncAt ?? ''));
    await this.context.globalState.update(LOCAL_MIRRORS_KEY, mirrors);
    return mirrors;
  }

  async registerLocalMirror(root: string): Promise<LocalMirrorRecord | undefined> {
    const mirror = await this.recordForMirrorRoot(root);
    if (!mirror) {
      return undefined;
    }
    const registry = await this.getRegisteredMirrors(false);
    const next = [
      mirror,
      ...registry.filter(item => normalizeRoot(item.root) !== normalizeRoot(root))
    ];
    await this.context.globalState.update(LOCAL_MIRRORS_KEY, next);
    await registerSharedMirror(root);
    return mirror;
  }

  async forgetLocalMirror(root: string): Promise<void> {
    const registry = await this.getRegisteredMirrors(false);
    const next = registry.filter(item => normalizeRoot(item.root) !== normalizeRoot(root));
    await this.context.globalState.update(LOCAL_MIRRORS_KEY, next);
  }

  async initializeGitRepository(root: string, commitMessage = 'Initial Overleaf mirror'): Promise<void> {
    await fs.mkdir(root, { recursive: true });
    await fs.writeFile(path.join(root, '.gitignore'), MIRROR_GITIGNORE_CONTENT, 'utf8');

    const hasGit = await exists(path.join(root, '.git'));
    if (!hasGit) {
      await runGit(root, ['init']);
      await runGit(root, ['add', '-A']);
      const staged = await runGit(root, ['diff', '--cached', '--quiet']).then(
        () => false,
        error => isGitDiffExitCode(error) ? true : Promise.reject(error)
      );
      if (staged) {
        await runGit(root, [
          '-c', 'user.name=Overleaf Codex',
          '-c', 'user.email=overleaf-codex@local',
          'commit',
          '-m', commitMessage
        ]);
      }
      await this.registerLocalMirror(root);
      return;
    }

    await runGit(root, ['add', '.gitignore']);
    await this.registerLocalMirror(root);
  }

  private async getRegisteredMirrors(cleanMissing = true): Promise<LocalMirrorRecord[]> {
    const stored = this.context.globalState.get<unknown>(LOCAL_MIRRORS_KEY, []);
    const raw = Array.isArray(stored) ? stored : [];
    if (!cleanMissing) {
      return raw.filter(isLocalMirrorRecord);
    }

    const mirrors: LocalMirrorRecord[] = [];
    for (const item of raw) {
      if (!isLocalMirrorRecord(item)) {
        continue;
      }
      const fresh = await this.recordForMirrorRoot(item.root);
      if (fresh) {
        mirrors.push(fresh);
      }
    }
    if (mirrors.length !== raw.length || mirrors.some((mirror, index) => mirror.lastSyncAt !== raw[index]?.lastSyncAt)) {
      await this.context.globalState.update(LOCAL_MIRRORS_KEY, mirrors);
    }
    return mirrors;
  }

  private async scanConfiguredRootMirrors(): Promise<LocalMirrorRecord[]> {
    const projectsRoot = this.getConfiguredProjectsRoot();
    const entries = await fs.readdir(projectsRoot, { withFileTypes: true }).catch(() => []);
    const mirrors: LocalMirrorRecord[] = [];
    for (const entry of entries) {
      if (!entry.isDirectory()) {
        continue;
      }
      const mirror = await this.recordForMirrorRoot(path.join(projectsRoot, entry.name));
      if (mirror) {
        mirrors.push(mirror);
      }
    }
    return mirrors;
  }

  private async recordForMirrorRoot(root: string): Promise<LocalMirrorRecord | undefined> {
    if (!await exists(manifestPath(root))) {
      return undefined;
    }
    const manifest = await readManifest(root).catch(() => undefined);
    if (!manifest) {
      return undefined;
    }
    return {
      root,
      name: manifest.projectName || path.basename(root),
      projectId: manifest.projectId,
      serverUrl: manifest.serverUrl,
      lastSyncAt: manifest.lastSyncAt
    };
  }

  private async writeInitialFile(
    client: OverleafClient,
    session: Awaited<ReturnType<OverleafClient['connectSocket']>>,
    projectId: string,
    targetRoot: string,
    file: ManifestFile
  ): Promise<void> {
    const targetPath = path.join(targetRoot, file.path);
    await fs.mkdir(path.dirname(targetPath), { recursive: true });

    if (file.entityType === 'doc') {
      const doc = await session.joinDoc(file.entityId);
      await fs.writeFile(targetPath, doc.content, 'utf8');
      file.version = doc.version;
      file.binary = !isTextLike(file.path);
      file.sha1 = sha1(doc.content);
      file.baseHash = await writeBaseDoc(targetRoot, file.entityId, doc.content);
      await session.leaveDoc(file.entityId).catch(() => undefined);
      return;
    }

    const content = await client.downloadProjectFile(projectId, file.entityId);
    await fs.writeFile(targetPath, content);
    file.binary = true;
    file.sha1 = sha1(content);
  }

  private async writeLocalVsCodeSettings(root: string, rootDocPath?: string, compiler?: string): Promise<void> {
    const settingsPath = path.join(root, '.vscode', 'settings.json');
    await fs.mkdir(path.dirname(settingsPath), { recursive: true });
    const rootFile = rootDocPath ? `./${rootDocPath}` : undefined;
    const rootDir = rootDocPath ? path.posix.dirname(rootDocPath) : '.';
    const texFile = rootDocPath ? path.posix.basename(rootDocPath) : '%DOC%';
    const engine = compiler === 'pdflatex' ? '-pdf' : compiler === 'lualatex' ? '-lualatex' : '-xelatex';
    const outputDir = '.overleaf-codex/local-build';
    const outputDirFromRootDoc = path.posix.relative(rootDir, outputDir) || '.';
    const workspaceFromRootDoc = path.posix.relative(rootDir, '.') || '.';
    const biberCacheDir = path.join(os.tmpdir(), 'overleaf-codex-biber', sha1(root).slice(0, 12));
    const searchPrefix = rootDir === '.'
      ? '.:src/source//:'
      : `.:${workspaceFromRootDoc}//:src/source//:`;
    const compileCommand = [
      `mkdir -p ${shellQuote(outputDir)}`,
      `mkdir -p ${shellQuote(biberCacheDir)}`,
      `cd ${shellQuote(rootDir)}`,
      [
        'find . -type d',
        "-not -path './.git*'",
        "-not -path './.overleaf-codex*'",
        "-not -path './.vscode*'",
        `-exec mkdir -p ${shellQuote(`${outputDirFromRootDoc}/{}`)} \\;`
      ].join(' '),
      [
        'latexmk',
        '-synctex=1',
        '-interaction=nonstopmode',
        '-file-line-error',
        engine,
        `-outdir=${shellQuote(outputDirFromRootDoc)}`,
        `-auxdir=${shellQuote(outputDirFromRootDoc)}`,
        shellQuote(texFile)
      ].join(' ')
    ].join(' && ');
    const settings = {
      'latex-workshop.latex.rootFile.doNotPrompt': true,
      'latex-workshop.latex.rootFile.useSubFile': false,
      ...(rootFile ? {
        'latex-workshop.latex.search.rootFiles.include': [rootFile.replace(/^\.\//, '')],
        'latex-workshop.latex.search.rootFiles.exclude': ['**/*.sty', '**/*.cls']
      } : {}),
      'latex-workshop.latex.recipe.default': 'latexmk (local mirror)',
      'latex-workshop.latex.autoBuild.run': 'onSave',
      'latex-workshop.latex.outDir': '%WORKSPACE_FOLDER%/.overleaf-codex/local-build',
      'latex-workshop.latex.tools': [
        {
          name: 'latexmk-local-mirror',
          command: 'bash',
          args: [
            '-lc',
            compileCommand
          ],
          env: {
            TEXINPUTS: searchPrefix,
            GINPUTS: searchPrefix,
            BIBINPUTS: searchPrefix,
            PAR_GLOBAL_TEMP: biberCacheDir,
            PAR_TEMP: biberCacheDir
          }
        }
      ],
      'latex-workshop.latex.recipes': [
        {
          name: 'latexmk (local mirror)',
          tools: ['latexmk-local-mirror']
        }
      ]
    };
    await fs.writeFile(settingsPath, `${JSON.stringify(settings, null, 2)}\n`, 'utf8');
  }

  private async writeLocalLatexmkRc(root: string, rootDocPath?: string): Promise<void> {
    const rootDir = rootDocPath ? path.posix.dirname(rootDocPath) : '.';
    const rcPath = path.join(root, rootDir, '.latexmkrc');
    const outputDir = '.overleaf-codex/local-build';
    const outputDirFromRootDoc = path.posix.relative(rootDir, outputDir) || '.';
    const workspaceFromRootDoc = path.posix.relative(rootDir, '.') || '.';
    const searchPrefix = rootDir === '.'
      ? '.:src/source//:'
      : `.:${workspaceFromRootDoc}//:src/source//:`;
    const biberCacheDir = path.join(os.tmpdir(), 'overleaf-codex-biber', sha1(root).slice(0, 12));
    const content = [
      '# Generated by Overleaf Codex for local VS Code/LaTeX Workshop builds.',
      '# This file is local-only and should not be synced back to Overleaf.',
      "if (-f 'latexmkrc') {",
      "  do './latexmkrc';",
      '}',
      'use File::Find;',
      'use File::Path qw(make_path);',
      `my $overleaf_codex_build_dir = ${perlSingleQuote(outputDirFromRootDoc)};`,
      `my $overleaf_codex_biber_cache = ${perlSingleQuote(biberCacheDir)};`,
      'make_path($overleaf_codex_build_dir);',
      'make_path($overleaf_codex_biber_cache);',
      'find({',
      '  wanted => sub {',
      '    return unless -d $_;',
      '    my $rel = $File::Find::name;',
      "    return if $rel eq '.';",
      "    $rel =~ s#^\\./##;",
      "    return if $rel =~ m#^\\.git(/|$)#;",
      "    return if $rel =~ m#^\\.overleaf-codex(/|$)#;",
      "    return if $rel =~ m#^\\.vscode(/|$)#;",
      '    make_path("$overleaf_codex_build_dir/$rel");',
      '  },',
      '  no_chdir => 1',
      "}, '.');",
      '$out_dir = $overleaf_codex_build_dir;',
      '$aux_dir = $overleaf_codex_build_dir;',
      `$ENV{'TEXINPUTS'} = ${perlSingleQuote(searchPrefix)} . ($ENV{'TEXINPUTS'} // '');`,
      `$ENV{'GINPUTS'} = ${perlSingleQuote(searchPrefix)} . ($ENV{'GINPUTS'} // '');`,
      `$ENV{'BIBINPUTS'} = ${perlSingleQuote(searchPrefix)} . ($ENV{'BIBINPUTS'} // '');`,
      "$ENV{'PAR_GLOBAL_TEMP'} = $overleaf_codex_biber_cache;",
      "$ENV{'PAR_TEMP'} = $overleaf_codex_biber_cache;",
      ''
    ].join('\n');
    await fs.mkdir(path.dirname(rcPath), { recursive: true });
    await fs.writeFile(rcPath, content, 'utf8');
  }
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function perlSingleQuote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

async function runGit(cwd: string, args: string[]): Promise<string> {
  const result = await execFileAsync('git', args, {
    cwd,
    encoding: 'utf8',
    maxBuffer: 1024 * 1024 * 10
  });
  return `${result.stdout ?? ''}${result.stderr ?? ''}`;
}

function isGitDiffExitCode(error: unknown): boolean {
  return Boolean(error)
    && typeof error === 'object'
    && (error as { code?: number }).code === 1;
}

function isLocalMirrorRecord(value: unknown): value is LocalMirrorRecord {
  return Boolean(value)
    && typeof value === 'object'
    && typeof (value as LocalMirrorRecord).root === 'string'
    && typeof (value as LocalMirrorRecord).projectId === 'string'
    && typeof (value as LocalMirrorRecord).serverUrl === 'string';
}

function normalizeRoot(root: string): string {
  return path.resolve(expandHome(root));
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

export function outputFileName(output: CompileOutputFile): string {
  if (output.path) {
    return output.path;
  }
  if (output.url) {
    return path.posix.basename(output.url.split('?')[0]);
  }
  return 'output.bin';
}
