import * as fs from 'fs/promises';
import * as os from 'os';
import * as path from 'path';
import { execFile } from 'child_process';
import { promisify } from 'util';
import { buildProjectTreeIndex } from './tree';
import { ensureLocalIgnoreFile, metadataPath, writeBaseDoc, writeManifest } from './manifest';
import type { ManifestFile, ProjectSummary } from './types';
import { OverleafClient } from './overleafClient';
import { expandHome, isTextLike, sanitizeProjectFolderName, sha1 } from './util';
import { registerSharedMirror } from './sharedState';
import { mapWithConcurrency, mapWithDynamicByteConcurrency, type DynamicByteReservation } from './syncHealthService';

const execFileAsync = promisify(execFile);

const AGENTS_CONTENT = `# AGENTS.md

This folder is a real local mirror of an Overleaf project.

- Edit LaTeX source files such as .tex, .bib, .sty and .cls normally.
- Do not edit .overleaf-codex/**; it contains sync metadata, build output and conflict copies.
- Edit .overleaf-codexignore to keep project-specific local or generated paths out of Overleaf sync.
- Do not upload or sync .vscode/**; it is local VS Code/LaTeX Workshop configuration only.
- Do not edit generated LaTeX outputs such as .aux, .log, .toc, .synctex.gz or PDFs unless explicitly asked.
- Prefer small, reviewable edits and keep paths stable when collaborators may also be editing in Overleaf.
`;

export const MIRROR_GITIGNORE_CONTENT = `# Generated by Overleaf Codex.
# Keep local sync/build metadata out of Git. Overleaf source files remain tracked.

.overleaf-codex/

# Local build outputs
*.aux
*.bbl
*.bcf
*.bcf-*
*.blg
*.fdb_latexmk
*.fls
*.lof
*.log
*.lot
*.out
*.run.xml
*.synctex
*.synctex.gz
*.synctex(busy)
*.toc
*.xdv
*-SAVE-ERROR
main.pdf
output.pdf

# Local credentials / OS noise
cookie*
.DS_Store
`;

export interface CreateProjectMirrorOptions {
  register?: (root: string) => Promise<unknown>;
  taskConcurrency?: number;
  maxInFlightBytes?: number;
}

export function projectMirrorRoot(parentRoot: string, project: ProjectSummary): string {
  return path.join(expandHome(parentRoot), sanitizeProjectFolderName(project.name, project.id));
}

export async function createProjectMirror(
  client: OverleafClient,
  project: ProjectSummary,
  parentRoot: string,
  options: CreateProjectMirrorOptions = {}
): Promise<string> {
  const targetRoot = projectMirrorRoot(parentRoot, project);
  await fs.mkdir(path.dirname(targetRoot), { recursive: true });
  try {
    await fs.mkdir(targetRoot);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new Error(`Mirror target already exists: ${targetRoot}`);
    }
    throw error;
  }

  let session: Awaited<ReturnType<OverleafClient['connectSocket']>> | undefined;
  try {
    session = await client.connectSocket(project.id);
    const joined = session.getProject();
    if (!joined) throw new Error('Realtime connection did not provide a project tree.');
    const index = buildProjectTreeIndex(client.getServerUrl(), project.id, project.name, joined);
    await mapWithConcurrency(
      index.folders.filter(folder => Boolean(folder.path)),
      options.taskConcurrency ?? 4,
      async folder => { await fs.mkdir(path.join(targetRoot, folder.path), { recursive: true }); }
    );
    await mapWithDynamicByteConcurrency(
      index.files,
      options.taskConcurrency ?? 4,
      options.maxInFlightBytes ?? 32 * 1024 * 1024,
      async (file, reservation) => writeInitialFile(client, session!, project.id, targetRoot, file, reservation)
    );
    for (const name of ['output', 'conflicts', path.join('base', 'docs'), 'trash']) {
      await fs.mkdir(metadataPath(targetRoot, name), { recursive: true });
    }
    await ensureLocalIgnoreFile(targetRoot);
    await writeManifest(targetRoot, index.manifest);
    await writeMirrorSupportFiles(targetRoot, index.manifest.rootDocPath, index.manifest.compiler);
    await initializeMirrorGitRepository(targetRoot, `Initial Overleaf mirror: ${project.name}`);
  } catch (error) {
    await fs.rm(targetRoot, { recursive: true, force: true });
    throw error;
  } finally {
    session?.disconnect();
  }
  await (options.register ?? registerSharedMirror)(targetRoot);
  return targetRoot;
}

async function writeInitialFile(
  client: OverleafClient,
  session: Awaited<ReturnType<OverleafClient['connectSocket']>>,
  projectId: string,
  root: string,
  file: ManifestFile,
  reservation?: DynamicByteReservation
): Promise<void> {
  const target = path.join(root, file.path);
  await fs.mkdir(path.dirname(target), { recursive: true });
  if (file.entityType === 'doc') {
    const joined = await session.joinDoc(file.entityId);
    try {
      await reservation?.reserve(Buffer.byteLength(joined.content, 'utf8'));
      await fs.writeFile(target, joined.content, 'utf8');
      file.version = joined.version;
      file.binary = !isTextLike(file.path);
      file.sha1 = sha1(joined.content);
      file.baseHash = await writeBaseDoc(root, file.entityId, joined.content);
    } finally {
      await session.leaveDoc(file.entityId).catch(() => undefined);
    }
  } else {
    const result = await client.downloadProjectFileToPath(projectId, file.entityId, target, {
      onSize: async size => { await reservation?.reserve(size); }
    });
    file.binary = true;
    file.sha1 = result.sha1;
    file.remoteSize = result.size;
    file.remoteBlobHash ??= result.gitBlobHash;
  }
}

export async function writeMirrorSupportFiles(root: string, rootDocPath?: string, compiler?: string): Promise<void> {
  await Promise.all([
    writeLocalVsCodeSettings(root, rootDocPath, compiler),
    writeLocalLatexmkRc(root, rootDocPath),
    fs.writeFile(path.join(root, 'AGENTS.md'), AGENTS_CONTENT, 'utf8')
  ]);
}

export async function initializeMirrorGitRepository(
  root: string,
  commitMessage = 'Initial Overleaf mirror'
): Promise<void> {
  await fs.mkdir(root, { recursive: true });
  await fs.writeFile(path.join(root, '.gitignore'), MIRROR_GITIGNORE_CONTENT, 'utf8');
  if (!await exists(path.join(root, '.git'))) {
    await runGit(root, ['init']);
    await runGit(root, ['add', '-A']);
    const staged = await runGit(root, ['diff', '--cached', '--quiet']).then(
      () => false,
      error => isGitDiffExitCode(error) ? true : Promise.reject(error)
    );
    if (staged) {
      await runGit(root, [
        '-c', 'user.name=Overleaf Codex',
        '-c', 'user.email=overleaf-codex@local',
        'commit',
        '-m', commitMessage
      ]);
    }
    return;
  }
  await runGit(root, ['add', '.gitignore']);
}

async function writeLocalVsCodeSettings(root: string, rootDocPath?: string, compiler?: string): Promise<void> {
  const settingsPath = path.join(root, '.vscode', 'settings.json');
  await fs.mkdir(path.dirname(settingsPath), { recursive: true });
  const rootFile = rootDocPath ? `./${rootDocPath}` : undefined;
  const rootDir = rootDocPath ? path.posix.dirname(rootDocPath) : '.';
  const texFile = rootDocPath ? path.posix.basename(rootDocPath) : '%DOC%';
  const engine = compiler === 'pdflatex' ? '-pdf' : compiler === 'lualatex' ? '-lualatex' : '-xelatex';
  const outputDir = '.overleaf-codex/local-build';
  const outputDirFromRootDoc = path.posix.relative(rootDir, outputDir) || '.';
  const workspaceFromRootDoc = path.posix.relative(rootDir, '.') || '.';
  const biberCacheDir = path.join(os.tmpdir(), 'overleaf-codex-biber', sha1(root).slice(0, 12));
  const searchPrefix = rootDir === '.' ? '.:src/source//:' : `.:${workspaceFromRootDoc}//:src/source//:`;
  const compileCommand = [
    `mkdir -p ${shellQuote(outputDir)}`,
    `mkdir -p ${shellQuote(biberCacheDir)}`,
    `cd ${shellQuote(rootDir)}`,
    [
      'find . -type d',
      "-not -path './.git*'",
      "-not -path './.overleaf-codex*'",
      "-not -path './.vscode*'",
      `-exec mkdir -p ${shellQuote(`${outputDirFromRootDoc}/{}`)} \\;`
    ].join(' '),
    [
      'latexmk', '-synctex=1', '-interaction=nonstopmode', '-file-line-error', engine,
      `-outdir=${shellQuote(outputDirFromRootDoc)}`,
      `-auxdir=${shellQuote(outputDirFromRootDoc)}`,
      shellQuote(texFile)
    ].join(' ')
  ].join(' && ');
  const settings = {
    'latex-workshop.latex.rootFile.doNotPrompt': true,
    'latex-workshop.latex.rootFile.useSubFile': false,
    ...(rootFile ? {
      'latex-workshop.latex.search.rootFiles.include': [rootFile.replace(/^\.\//, '')],
      'latex-workshop.latex.search.rootFiles.exclude': ['**/*.sty', '**/*.cls']
    } : {}),
    'latex-workshop.latex.recipe.default': 'latexmk (local mirror)',
    'latex-workshop.latex.autoBuild.run': 'onSave',
    'latex-workshop.latex.outDir': '%WORKSPACE_FOLDER%/.overleaf-codex/local-build',
    'latex-workshop.latex.tools': [{
      name: 'latexmk-local-mirror', command: 'bash', args: ['-lc', compileCommand],
      env: {
        TEXINPUTS: searchPrefix,
        GINPUTS: searchPrefix,
        BIBINPUTS: searchPrefix,
        PAR_GLOBAL_TEMP: biberCacheDir,
        PAR_TEMP: biberCacheDir
      }
    }],
    'latex-workshop.latex.recipes': [{ name: 'latexmk (local mirror)', tools: ['latexmk-local-mirror'] }]
  };
  await fs.writeFile(settingsPath, `${JSON.stringify(settings, null, 2)}\n`, 'utf8');
}

async function writeLocalLatexmkRc(root: string, rootDocPath?: string): Promise<void> {
  const rootDir = rootDocPath ? path.posix.dirname(rootDocPath) : '.';
  const rcPath = path.join(root, rootDir, '.latexmkrc');
  const outputDir = '.overleaf-codex/local-build';
  const outputDirFromRootDoc = path.posix.relative(rootDir, outputDir) || '.';
  const workspaceFromRootDoc = path.posix.relative(rootDir, '.') || '.';
  const searchPrefix = rootDir === '.' ? '.:src/source//:' : `.:${workspaceFromRootDoc}//:src/source//:`;
  const biberCacheDir = path.join(os.tmpdir(), 'overleaf-codex-biber', sha1(root).slice(0, 12));
  const content = [
    '# Generated by Overleaf Codex for local VS Code/LaTeX Workshop builds.',
    '# This file is local-only and should not be synced back to Overleaf.',
    "if (-f 'latexmkrc') {", "  do './latexmkrc';", '}',
    'use File::Find;', 'use File::Path qw(make_path);',
    `my $overleaf_codex_build_dir = ${perlSingleQuote(outputDirFromRootDoc)};`,
    `my $overleaf_codex_biber_cache = ${perlSingleQuote(biberCacheDir)};`,
    'make_path($overleaf_codex_build_dir);', 'make_path($overleaf_codex_biber_cache);',
    'find({', '  wanted => sub {', '    return unless -d $_;',
    '    my $rel = $File::Find::name;', "    return if $rel eq '.';", "    $rel =~ s#^\\./##;",
    "    return if $rel =~ m#^\\.git(/|$)#;", "    return if $rel =~ m#^\\.overleaf-codex(/|$)#;",
    "    return if $rel =~ m#^\\.vscode(/|$)#;", '    make_path("$overleaf_codex_build_dir/$rel");',
    '  },', '  no_chdir => 1', "}, '.');",
    '$out_dir = $overleaf_codex_build_dir;', '$aux_dir = $overleaf_codex_build_dir;',
    `$ENV{'TEXINPUTS'} = ${perlSingleQuote(searchPrefix)} . ($ENV{'TEXINPUTS'} // '');`,
    `$ENV{'GINPUTS'} = ${perlSingleQuote(searchPrefix)} . ($ENV{'GINPUTS'} // '');`,
    `$ENV{'BIBINPUTS'} = ${perlSingleQuote(searchPrefix)} . ($ENV{'BIBINPUTS'} // '');`,
    "$ENV{'PAR_GLOBAL_TEMP'} = $overleaf_codex_biber_cache;",
    "$ENV{'PAR_TEMP'} = $overleaf_codex_biber_cache;", ''
  ].join('\n');
  await fs.mkdir(path.dirname(rcPath), { recursive: true });
  await fs.writeFile(rcPath, content, 'utf8');
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function perlSingleQuote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

async function runGit(cwd: string, args: string[]): Promise<string> {
  const result = await execFileAsync('git', args, { cwd, encoding: 'utf8', maxBuffer: 1024 * 1024 * 10 });
  return `${result.stdout ?? ''}${result.stderr ?? ''}`;
}

function isGitDiffExitCode(error: unknown): boolean {
  return Boolean(error) && typeof error === 'object' && (error as { code?: number }).code === 1;
}

async function exists(target: string): Promise<boolean> {
  return fs.stat(target).then(() => true, () => false);
}
